[packages]
aiohttp = "3.8.5"
aiosignal = "1.3.1"
async-timeout = "4.0.2"
attrs = "23.1.0"
certifi = "2023.7.22"
chardet = "3.0.4"
charset-normalizer = "3.2.0"
cmake = "3.27.0"
DateTime = "5.2"
ffmpeg = "1.4"
ffmpeg-python = "0.2.0"
filelock = "3.12.2"
frozenlist = "1.4.0"
future = "0.18.3"
googletrans = "4.0.0rc1"
h11 = "0.9.0"
h2 = "3.2.0"
hpack = "3.0.0"
hstspreload = "2023.1.1"
httpcore = "0.9.1"
httpx = "0.13.3"
hyperframe = "5.2.0"
idna = "2.10"
iniconfig = "2.0.0"
Jinja2 = "3.1.2"
langdetect = "1.0.9"
lit = "16.0.6"
llvmlite = "0.40.1"
MarkupSafe = "2.1.3"
meeting-assistant = { version = "0.1", path = "/home/mvanzulli/Repositories/gitHub/mine/Meeeting_Assistant/src" }
more-itertools = "10.0.0"
mpmath = "1.3.0"
multidict = "6.0.4"
networkx = "3.1"
numba = "0.57.1"
numpy = "1.24.4"
nvidia-cublas-cu11 = "11.10.3.66"
nvidia-cuda-cupti-cu11 = "11.7.101"
nvidia-cuda-nvrtc-cu11 = "11.7.99"
nvidia-cuda-runtime-cu11 = "11.7.99"
nvidia-cudnn-cu11 = "8.5.0.96"
nvidia-cufft-cu11 = "10.9.0.58"
nvidia-curand-cu11 = "10.2.10.91"
nvidia-cusolver-cu11 = "11.4.0.1"
nvidia-cusparse-cu11 = "11.7.4.91"
nvidia-nccl-cu11 = "2.14.3"
nvidia-nvtx-cu11 = "11.7.91"
openai = "0.27.8"
openai-whisper = "20230314"
packaging = "23.1"
pip = "22.3.1"
pluggy = "1.2.0"
pytest = "7.4.0"
pytz = "2023.3"
PyYAML = "6.0.1"
regex = "2023.6.3"
requests = "2.31.0"
rfc3986 = "1.5.0"
setuptools = "65.5.0"
six = "1.16.0"
sniffio = "1.3.0"
sympy = "1.12"
tiktoken = "0.3.1"
torch = "2.0.1"
tqdm = "4.65.0"
triton = "2.0.0"
typing_extensions = "4.7.1"
urllib3 = "2.0.4"
wheel = "0.41.0"
yarl = "1.9.2"
zope.interface = "6.0"
